### ISSUE TITLE
Malformed update JSON

### ISSUE THREAD

**Issue by ChiefArug** [talhanation/smallships#17]
```
[Forge Version Check/INFO]: [smallships] Starting version check at https://raw.githubusercontent.com/talhanation/Ship-Mod/main/update.json
[Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 10 column 4 path $.
	at com.google.gson.Gson.fromJson(Gson.java:978) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%23121!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.2-43.2.0.jar%231226!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.2-43.2.0.jar%231226!/:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 10 column 4 path $.
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23121!/:?]
	... 6 more
```
Nothing crash worthy, just an unneeded stacktrace in the logs

**Comment by brooswit** [comment]
This appears to be keeping my server from being able to start. This is the last error before the server freezes while starting
