### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Bawnorton** [talhanation/smallships#20]
Hi, I have been getting reports that the ships in this mod are causing ticking exceptions, my mod handles ticking entities by killing them to stop the server from bricking, but just for a sanity check, the crash does happen with the module disabled. 

When Neruina enabled:

![image](https://github.com/talhanation/smallships/assets/18416784/e851a64f-7c22-4b0f-b815-0d7e253c0773)

Crash when Neruina disabled:
<details>

<summary>Log</summary>

```
24.11 23:52:20 [Server] Server thread/ERROR Encountered an unexpected exception
24.11 23:52:20 [Server] INFO net.minecraft.util.crash.CrashException: Ticking entity
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:901) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:283) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:824) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
24.11 23:52:20 [Server] INFO Caused by: com.bawnorton.neruina.exception.DoNotHandleException: Neruina skipped handling an entity because it was disabled in the config
24.11 23:52:20 [Server] INFO 	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:120) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.world.World.wrapOperation$eob000$neruina$catchTickingEntities(World.java:14048) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.world.World.tickEntity(World.java:480) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:385) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.world.EntityList.forEach(EntityList.java:54) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:353) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:897) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	... 5 more
24.11 23:52:20 [Server] INFO Caused by: java.util.ConcurrentModificationException
24.11 23:52:20 [Server] INFO 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
24.11 23:52:20 [Server] INFO 	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.screen.ScreenHandler.updateTrackedSlot(ScreenHandler.java:218) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.screen.ScreenHandler.sendContentUpdates(ScreenHandler.java:176) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity.java:472) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.entity.Entity.tickRiding(Entity.java:2039) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.entity.LivingEntity.tickRiding(LivingEntity.java:2866) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.entity.player.PlayerEntity.tickRiding(PlayerEntity.java:535) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.world.ServerWorld.tickPassenger(ServerWorld.java:762) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:743) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.world.World.mixinextras$bridge$accept$204(World.java) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.world.World.wrapOperation$eob000$neruina$catchTickingEntities(World.java:14048) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.world.World.tickEntity(World.java:480) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:385) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.world.EntityList.forEach(EntityList.java:54) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:353) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:897) ~[server-intermediary.jar:?]
24.11 23:52:20 [Server] INFO 	... 5 more
```
associated log: https://paste.shockbyte.com/legicunugequwejajeci
</details>

I tried digging around in your source but I can't find a clear indication of where it originates from.

**Comment by Atlasroar** [comment]
2 years later and updating this to say that i think it has something to do with the inventory on the ships. everytime i go to check the second page Neurina kicks me from my singleplayer world to save me.
it's also on multiple occasions frozen me in place (locking me in the boat lol) to prevent a server crash
